[formatter.nix]
command = "alejandra"
includes = ["*.nix"]
excludes = [
  "overrides/nodejs/electron/*",
  "src/templates/translators/*",
  "src/modules/_template/*",
]

[formatter.py]
command = "black"
includes = ["*.py"]
