# To re-generate this file, run:
#   nix run github:nix-community/dream2nix#detect-projects $source
# ... where `$source` points to the source of your project.

["gipetto/cowsay"]
name = "gipetto/cowsay"
relPath = ""
subsystem = "php"
translator = "composer-lock"
translators = [ "composer-lock", "composer-json",]

["gipetto/cowsay".subsystemInfo]
