# To re-generate this file, run:
#   nix run github:nix-community/dream2nix#detect-projects $source
# ... where `$source` points to the source of your project.

[ripgrep]
name = "ripgrep"
relPath = ""
subsystem = "rust"
translator = "cargo-lock"
translators = [ "cargo-lock", "cargo-toml",]
builder = "crane"

[ripgrep.subsystemInfo]
workspaceMembers = [ "crates/globset", "crates/grep", "crates/cli", "crates/matcher", "crates/pcre2", "crates/printer", "crates/regex", "crates/searcher", "crates/ignore",]
[[ripgrep.subsystemInfo.crates]]
name = "ripgrep"
relPath = ""
version = "13.0.0"

[[ripgrep.subsystemInfo.crates]]
name = "grep-cli"
relPath = "crates/cli"
version = "0.1.6"

[[ripgrep.subsystemInfo.crates]]
name = "globset"
relPath = "crates/globset"
version = "0.4.7"

[[ripgrep.subsystemInfo.crates]]
name = "grep"
relPath = "crates/grep"
version = "0.2.8"

[[ripgrep.subsystemInfo.crates]]
name = "ignore"
relPath = "crates/ignore"
version = "0.4.18"

[[ripgrep.subsystemInfo.crates]]
name = "grep-matcher"
relPath = "crates/matcher"
version = "0.1.5"

[[ripgrep.subsystemInfo.crates]]
name = "grep-pcre2"
relPath = "crates/pcre2"
version = "0.1.5"

[[ripgrep.subsystemInfo.crates]]
name = "grep-printer"
relPath = "crates/printer"
version = "0.1.6"

[[ripgrep.subsystemInfo.crates]]
name = "grep-regex"
relPath = "crates/regex"
version = "0.1.9"

[[ripgrep.subsystemInfo.crates]]
name = "grep-searcher"
relPath = "crates/searcher"
version = "0.1.8"

