# To re-generate this file, run:
#   nix run github:nix-community/dream2nix#detect-projects $source
# ... where `$source` points to the source of your project.

[linemd]
name = "linemd"
relPath = ""
subsystem = "rust"
translator = "cargo-lock"
translators = [ "cargo-lock", "cargo-toml",]

[[linemd.subsystemInfo.crates]]
name = "linemd"
relPath = ""
version = "0.4.0"

